version: "3.9" # optional since v1.27.0
services:
  redis:
    image: redis

  api:
    build: api

    ports:
      - "127.0.0.1:8002:8002"

    volumes:
      - ./api:/app

    command: uvicorn scorer.asgi:application --reload --host 0.0.0.0 --port 8002

  worker:
    build: api

    volumes:
      - ./api:/app

    command: celery -A scorer worker -l DEBUG

  verifier:
    build: verifier
