version: "3.9" # optional since v1.27.0
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  api:
    build: api

    ports:
      - "127.0.0.1:8002:8002"

    volumes:
      - ./api:/app

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CERAMIC_CACHE_CACAO_VALIDATION_URL=http://verifier:8001/verify

    command: uvicorn scorer.asgi:application --reload --host 0.0.0.0 --port 8002

  worker:
    build: api

    volumes:
      - ./api:/app

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

    command: celery -A scorer worker -l DEBUG

  interface:
    build: interface

    ports:
      - "127.0.0.1:3001:3000"

  verifier:
    build: verifier

  postgres:
    image: postgres:12.3-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: passport_scorer
      POSTGRES_PASSWORD: passport_scorer_pwd
      POSTGRES_DB: passport_scorer
      PGDATA: /db_data

    volumes:
      - ./postgres_db_data:/db_data
